import {
  StyleSheet,
} from 'react-native';
import { colors, fonts, spacing, radius } from '@/constants/theme';
export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: colors.background },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingTop: 60,
    paddingHorizontal: spacing.lg,
    paddingBottom: spacing.md,
    gap: spacing.md,
  },
  backBtn: {
    width: 40,
    height: 40,
    borderRadius: radius.sm,
    backgroundColor: colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: colors.border,
  },
  headerTitle: {
    fontFamily: fonts.semiBold,
    fontSize: 18,
    color: colors.textPrimary,
  },
  scroll: { flex: 1 },
  scrollContent: {
    paddingHorizontal: spacing.lg,
    paddingBottom: 48,
    gap: spacing.xl,
  },
  section: { gap: spacing.sm },
  sectionLabel: {
    fontFamily: fonts.semiBold,
    fontSize: 15,
    color: colors.textPrimary,
  },
  textInput: {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    padding: spacing.md,
    fontFamily: fonts.regular,
    fontSize: 15,
    color: colors.textPrimary,
    minHeight: 90,
    textAlignVertical: 'top',
  },
  textInputError: { borderColor: colors.error },
  charCount: {
    fontFamily: fonts.regular,
    fontSize: 12,
    color: colors.textMuted,
    textAlign: 'right',
  },
  errorText: {
    fontFamily: fonts.regular,
    fontSize: 13,
    color: colors.error,
  },
  chipRow: { flexDirection: 'row', gap: spacing.sm, flexWrap: 'wrap' },
  chip: {
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    borderRadius: radius.full,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
  },
  chipActive: { backgroundColor: colors.accent, borderColor: colors.accent },
  chipText: { fontFamily: fonts.semiBold, fontSize: 14, color: colors.textSecondary },
  chipTextActive: { color: colors.white },
  timeRow: { gap: spacing.sm, paddingRight: spacing.md },
  timeChip: {
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    borderRadius: radius.full,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
  },
  timeChipActive: { backgroundColor: colors.accentSoft, borderColor: colors.accent },
  timeChipText: { fontFamily: fonts.regular, fontSize: 13, color: colors.textSecondary },
  timeChipTextActive: { color: colors.accent, fontFamily: fonts.semiBold },
  summaryCard: {
    backgroundColor: colors.surface,
    borderRadius: radius.md,
    padding: spacing.md,
    borderWidth: 1,
    borderColor: colors.border,
    gap: spacing.sm,
  },
  summaryTitle: {
    fontFamily: fonts.semiBold,
    fontSize: 12,
    color: colors.textMuted,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    marginBottom: 4,
  },
  summaryLine: { fontFamily: fonts.regular, fontSize: 14, color: colors.textSecondary },
  summaryValue: { fontFamily: fonts.semiBold, color: colors.textPrimary },
  ctaButton: { borderRadius: radius.lg, overflow: 'hidden' },
  ctaGradient: { paddingVertical: spacing.md + 4, alignItems: 'center' },
  ctaText: { fontFamily: fonts.bold, fontSize: 17, color: colors.white, letterSpacing: 0.2 },
});